# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-18 16:04
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_otp.util


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_verificationdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationdevice',
            name='last_t',
            field=models.BigIntegerField(default=-1, help_text='The t value of the latest verified token.         The next token must be at a higher time step.         It makes sure a token is used only once.'),
        ),
        migrations.AddField(
            model_name='verificationdevice',
            name='unverified_phone',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='phone',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='verificationdevice',
            name='secret_key',
            field=models.CharField(default=accounts.models.default_key, help_text='Hex-encoded secret key to generate totp tokens.', max_length=40, unique=True, validators=[django_otp.util.hex_validator]),
        ),
        migrations.AlterField(
            model_name='verificationdevice',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
